# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Reykjavik Summer of Cool Logic 2024 (SCooL 2024)
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Reykjavik Summer of Cool Logic 2024 (SCooL 2024), Reykjavik 10-21/6 2024
# baseurl: "/reykjavik-logic-2024" # the subpath of your site, e.g. /blog
# url: "http://icetcs.ru.is" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: ./_sass

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/
  pc:
    output: true
    permalink: /:collection/:title/
  sc:
    output: true
    permalink: /:collection/:title/
  pl:
    output: true
    permalink: /:collection/:title/
  dates:
    output: true
    permalink: /:collection/:title/

conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    # logo:
    #   name: Digital Society Switzerland
    #   # img: ''
    #   url: 'https://digitale-gesellschaft.ch/'
    links:
      - name: SCooL
        relative_url: /
      - name: NLS
        relative_url: /NLS/
      - name: SLSS
        relative_url: /SLSS/
      - name: GandALF
        relative_url: /GandALF/
        menu:
        - name: About
          relative_url: /GandALF/
        - name: CFP
         # disabled: true
          relative_url: /cfp/
        - name: Previous editions
         # disabled: true
          relative_url: /previous/
        - name: Program
          disabled: true
          menu:
          - name: Schedule
            relative_url: /program/
 # bGDWhYOEbyOoVye
      - name: Location
        relative_url: /location/
      #- name: Previous Editions
       # menu:
        #  - name: 2024 (current)
         #   disabled: true
          # - name: 2018
          #   relative_url: /2018/
      - name: Registration
        disabled: true
        # menu:
        #   - name: Fees
        #     relative_url: /fees/
        #   - name: Registration Form
        #     absolute_url: https://kom.eventsair.com/logic-colloquium/logic22reg/Site/Register
      - name: ASL sponsorship
        relative_url: /ASL/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Live indications
  live:
    date: 27.06.2022
    timezone: GMT
    time_stop: 240      # in minutes
    streaming:
      time_pause:   60  # in minutes
      time_prepend:  5  # in minutes
      time_extend:   5  # in minutes
    demo: false

  map:
    # Initial map center point
    home_coord: 64.12393455413351, -21.92699124546256
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 14

  talks:
    # Talk categories
    main_categories:
      - name: Talk
        color: warning
      - name: Plenary Talk
        color: primary
      - name: Tutorial
        color: success
      - name: Special Session
        color: info
      - name: Break
        color: light
      - name: Event
        color: danger

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: true
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: false

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 10 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true

  important_dates:
    # - name: "Registration Opens"
    #   time: "TBA"
    - name: "Deadline for Abstract Submission"
      time: "31<sup>st</sup> of March"
    # - name: "Notifications"
    #   time: "TBA"
    # - name: "Camera-Ready Abstracts Due"
    #   time: "TBA"
    - name: "Deadline for Early Registration"
      time: "1<sup>st</sup> of June"
    - name: "Start of the Conference"
      time: "27<sup>th</sup> of June"
    - name: "End of the Conference"
      time: "1<sup>st</sup> of July"
  early_fees:
    - name: Regular
      amount: 350
    - name: Student
      amount: 270
    - name: Online
      amount: 20
  late_fees:
    - name: Regular
      amount: 430
    - name: Student
      amount: 320
    - name: Online
      amount: 40
      # comment: " (from June 20, 2022)"

  special_sessions:
    - name: Set Theory
      keyword: st
    - name: Proof Theory and Ordinal Analysis
      keyword: pt
    - name: Reverse Mathematics and Combinatorial Principles
      keyword: rm
    - name: Model Theory
      keyword: mt
    - name: Computer Science Logic
      keyword: csl
    - name: Philosophy of Mathematics
      keyword: pm

  plenary:
    - name: Set Theory
      keyword: st
    - name: Model Theory
      keyword: mt
    - name: Computer Science Logic
      keyword: csl
    - name: Proof Theory
      keyword: pt
    - name: Computability Theory
      keyword: ct
    - name: Philosophy
      keyword: pm
