title: Logic Colloquium 2022
preposition: at
description: >-
 The Logic Colloquium is the European Summer Meeting of the Association for Symbolic Logic <br> 
 Reykjavik, Iceland, 27 June - 1 July 2022
baseurl: "/lc2022" # the subpath of your site, e.g. /blog
url: "http://icetcs.ru.is" # the base hostname & protocol for your site, e.g. https://example.com

theme: jekyll-theme-conference

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: pc
    values:
      layout: pc
  - scope:
      path: ""
      type: rooms
    values:
      layout: room
  - scope:
      path: ""
      type: dates
    values:
      layout: important_dates


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    # logo:
    #   name: Digital Society Switzerland
    #   # img: ''
    #   url: 'https://digitale-gesellschaft.ch/'
    links:
      - name: Home
        menu:
        - name: About
          relative_url: /
        - name: Important Dates
          relative_url: /important_dates/
        - name: Program Committee
          relative_url: /pc/
      - name: CFP
        relative_url: /cfp/
      - name: Program
        disabled: true
        menu:
        - name: Schedule
          relative_url: /program/
 # bGDWhYOEbyOoVye
          disabled: false
        - name: Plenary Speakers
          relative_url: /plenary/
          disabled: false
        - name: Special Sessions
          relative_url: /special_sessions/
        # - name: Talks
        #   relative_url: /talks/
        #   disabled: true
        # - name: Speakers
        #   relative_url: /speakers/
        #   disabled: true
      - name: Location
        relative_url: /location/
      - name: Previous Editions
        menu:
          - name: 2022 (current)
            disabled: true
          - name: 2021
            absolute_url: https://lc2021.pl/
          - name: 2019
            absolute_url: https://lc2019.cz/ 
          - name: 2018
            absolute_url: https://lc18.uniud.it/ 
          - name: 2017
            absolute_url: https://www.math-stockholm.se/konferenser-och-akti/logic-in-stockholm-2/logic-colloquium-201/logic-colloquium-2017-august-14-20-1.717629 
          # - name: 2018
          #   relative_url: /2018/
      - name: Registration
        menu:
          - name: Fees
            relative_url: /fees/
          - name: Registration Form
            absolute_url: https://kom.eventsair.com/logic-colloquium/logic22reg/Site/Register
